validate-website(1)
===================

NAME
----
validate-website - Web crawler for checking the validity of your documents

SYNOPSIS
--------
*validate-website* ['OPTIONS']

DESCRIPTION
-----------
validate-website is a web crawler for checking the markup validity with XML
Schema / DTD and not found urls.
HTML5 support with Validator.nu Web Service.

OPTIONS
-------
*-s*, *--site* 'SITE'::
  Website to crawl (Default: http://localhost:3000/)
*-u*, *--user-agent* 'USERAGENT'::
  Change user agent (Default: Spidr.user_agent)
*-e*, *--exclude* 'EXCLUDE'::
  Url to exclude (ex: 'redirect|news')
*-i*, *--ignore* 'IGNORE'::
  Ignore certain validation errors (ex: 'autocorrect')
*-c*, *--cookies* 'COOKIES'::
  Set defaults cookies
*-m*, *--[no-]markup*::
  Markup validation (Default: true)
*--css-syntax*::
  Css validation (Default: false)
*-n*, *--not-found*::
  Log not found url (Default: false)
*--[no-]color*::
  Show colored output (Default: true)
*-x*, *--html5-validator* 'VALIDATOR'::
  Change default html5 validator engine (ex: tidy or nu)
*-5*, *--html5-validator-service-url* 'URL'::
  Change default html5 validator service URL for "nu" engine
*-v*, *--verbose*::
  Show detail of validator errors (Default: false).
*-h*, *--help*::
  Show help message and exit.

EXIT STATUS
-----------
0::
  Markup is valid and no 404 found.
64::
  Not valid markup found.
65::
  There are pages not found.
66::
  There are not valid markup and pages not found.

AUTHOR
------
Laurent Arnoud mailto:laurent@spkdev.net[Laurent Arnoud]

LICENSE
-------
The MIT License

Copyright (c) 2009-2017 mailto:laurent@spkdev.net[Laurent Arnoud]

// vim: set syntax=asciidoc:
